[pytest]
addopts = --html=report.html --self-contained-html
markers =
    smoke: smoke test cases
    trading: trading test cases
    rande: retail and ecommerse
    mob:mobile app and devlopment
    ai:ai tab

 -m